export const ORBIT_VELOCITY_SCALE = 21600000;
export const SUN_DIAMETER = 1392684;
export const SUN_SIMULATED_DIAMETER = 15;
export const SIZE_SCALE = SUN_DIAMETER / SUN_SIMULATED_DIAMETER;
export const PLANET_SCALE = SIZE_SCALE / 10;
export const STAR_FIELD_COUNT = 30000;
export const ASTEROID_SCENE_DIAMETER = 17370;
